### ISSUE TITLE
Please change "नमस्कार l" to "नमस्कार." is the correct way of writing.

### ISSUE THREAD

**Issue by SarveshDevrukhkar** [gce-india/gce-india.github.io#29]
On a [GCE India Website](https://gce-india.github.io/) there is one wrongly written text. I think we should correct that.

![Screenshot (34)](https://user-images.githubusercontent.com/79737447/230035820-5013806a-a93d-4363-9141-04e017c709de.png)

In a **Marathi** language, this "." (Period) sign is used as the end of a line or full stop.

This "|" (pipe) sign is used in **Hindi** as the end of a line or a full stop.

So, Writing **"नमस्कार."** instead of **"नमस्कार |"** is the correct way of writing.

`Incorrect: नमस्कार|`
`Correct: नमस्कार.`

**Please Correct that!**

**Comment by SarveshDevrukhkar** [comment]
If I can change that text then, please give me the link to that file, and I will correct that. So, I can contribute something 😄

PS: I tried to search for the file but it's not found.

**Comment by paramsiddharth** [comment]
@SAD0XER Hi! 💓 Thank you for making the issue. The file is here: [`src/constants.ts`](https://github.com/gce-india/gce-india.github.io/blob/main/src/constants.ts).

Feel free to make a PR if you'd like to contribute. :) I'll assign the issue to you.

**Comment by paramsiddharth** [comment]
Resolved by #32.
